// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	ID       string `json:"id"`
	Sender   string `json:"sender"`
	Receiver string `json:"receiver"`
}

type Feelr struct {
	ID        string    `json:"id"`
	Question  string    `json:"question"`
	Timestamp time.Time `json:"timestamp"`
	Topic     string    `json:"topic"`
}

type Message struct {
	Chat           string    `json:"chat"`
	Sender         string    `json:"sender"`
	Text           *string   `json:"text"`
	Feelr          *string   `json:"feelr"`
	SenderAnswer   *string   `json:"senderAnswer"`
	ReceiverAnswer *string   `json:"receiverAnswer"`
	Timestamp      time.Time `json:"timestamp"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
